[package]
name = "region_actuator"
version = "0.0.1"
authors = ["Damon Rolfs <drolfs@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
#[[examples]]
#name = "grpc-raft-stub"
#path = "examples/raft_grpc_stub.rs"

[dependencies]
actix-web = "1.0.8"
actix-web-actors = "1.0.2"
actix-web-codegen = "0.2"
actix-cors = "0.1.0"
actix-files = "0.1.6"
tempfile = "3"
#frunk = "0.3"
#hash_ring = "0.1"
hash_ring = { git = "https://github.com/oronsh/rust-hash-ring.git"}
byteorder = "1.3"
bytes = "0.4"
rust-crypto = "0.2"
fasthash = "0.4"
config = "0.9"
rocksdb = "0.13"

actix = "0.8"
actix-rt = "1.0.0"
actix-raft = "0.4"
tokio = "0.1"
#tokio = { version = "0.2", features = ["macros", "sync", "stream", "time"]}
#tokio-util = { version = "0.3", features = ["codec"] }
#tokio = { version = "0.2", features = ["macros"] }
#futures = "0.3"
futures = "0.1"
tonic = "0.1"
prost = "0.6"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
rmp = "0.8"
rmp-serde = "0.14"
#serde_cbor = "0.11"
log = "0.4"
env_logger = "0.7"
#tracing = "0.1"
#tracing-futures = "0.2"
#tracing-subscriber = "0.2"
#tracing-timing = "0.4"
structopt = "0.3"
hocon = "0.3"

[build-dependencies]
tonic-build = "0.1.0"

